# Spring properties
spring:
  application:
     name: users-service  # Service registers under this name
  freemarker:
    enabled: false           # Ignore Eureka dashboard FreeMarker templates
  thymeleaf:
    cache: false             # Allow Thymeleaf templates to be reloaded at runtime
    prefix: classpath:/templates/    # Trailing / mandatory
                             # Template location for this application only
  datasource:
    url: jdbc:mysql://localhost:3306/downfall?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
  jackson:
    time-zone: America/Santiago
    locale: es_CL
logging:
  level:
    org:
      hibernate:
        SQL: debug
              
# Map the error path to error template (for Thymeleaf)
error:
  path=/error

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 2222   # HTTP (Tomcat) port



